packages:
  - packages/*
  - crates/*
  - examples/*

catalog:
  typescript: ^5.8.3
  '@types/node': 22.16.0
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild
