packages:
  - packages/*
  - crates/*
  - examples/*

catalog:
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitest/coverage-v8': ^3.2.4
  react: ^19.2.1
  react-dom: ^19.2.1
  typescript: ^5.9.3
  vitest: ^4.0.15

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - esbuild
