packages:
- 'packages/*'
- 'crates/*'
- 'examples/*'

catalog:
  typescript: ^5.8.3

  '@types/node': ^22.15.11

  # react
  react: &react ^19.1.0
  'react-dom': *react
  '@types/react': ^19.1.3
  '@types/react-dom': ^19.1.0

  # vitest
  vitest: &vitest "^3.1.3"
  '@vitest/coverage-v8': *vitest

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild