packages:
  - packages/*
  - crates/*
  - examples/*

catalog:
  '@types/node': ^22.18.0
  '@types/react': ^19.1.11
  '@types/react-dom': ^19.1.8
  '@vitest/coverage-v8': ^3.2.4
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ^5.9.2
  vitest: ^3.2.4

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild

patchedDependencies:
  rspack-chain: patches/rspack-chain.patch
