packages:
  - packages/*
  - crates/*
  - examples/*

catalog:
  '@types/node': ^22.18.7
  '@types/react': ^19.1.16
  '@types/react-dom': ^19.1.9
  '@vitest/coverage-v8': ^3.2.4
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ^5.9.2
  vitest: ^3.2.4

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - esbuild
