packages:
- 'packages/*'
- 'crates/*'
- 'examples/*'

catalog:
  typescript: ^5.7.2
  '@types/node': ^22.10.2
  react: ^19.0.0
  'react-dom': ^19.0.0
  '@types/react': ^19.0.2
  '@types/react-dom': ^19.0.2
