packages:
- 'packages/*'
- 'crates/*'
- 'examples/*'

catalog:
  typescript: ^5.8.2

  '@types/node': ^22.13.14

  # react
  react: &react ^19.0.0
  'react-dom': *react
  '@types/react': ^19.0.12
  '@types/react-dom': ^19.0.4

  # vitest
  vitest: &vitest "^3.0.9"
  '@vitest/coverage-v8': *vitest

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild