packages:
- 'packages/*'
- 'crates/*'
- 'examples/*'

catalog:
  typescript: ^5.7.3

  '@types/node': ^22.10.8

  # react
  react: &react ^19.0.0
  'react-dom': *react
  '@types/react': ^19.0.7
  '@types/react-dom': ^19.0.3

  # vitest
  vitest: &vitest "^3.0.3"
  '@vitest/coverage-v8': *vitest
