packages:
  - packages/*
  - crates/*
  - examples/*

catalog:
  '@types/node': ^24.9.2
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitest/coverage-v8': ^3.2.4
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
  vitest: ^4.0.5

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - esbuild
