packages:
  - packages/*
  - crates/*
  - examples/*
  - napi/*

catalog:
  typescript: ^5.8.3

  '@types/node': ^22.15.29

  # react
  react: &react ^19.1.0
  'react-dom': *react
  '@types/react': ^19.1.7
  '@types/react-dom': ^19.1.6

  # vitest
  vitest: &vitest "^3.2.3"
  '@vitest/coverage-v8': *vitest

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild