packages:
  - packages/*
  - crates/*
  - examples/*

catalog:
  '@types/node': ^24.12.2
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitest/coverage-v8': ^4.1.5
  react: ^19.2.5
  react-dom: ^19.2.5
  typescript: ^6.0.3
  vitest: ^4.1.5

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - esbuild

verifyDepsBeforeRun: install