/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function bundlessDtsAsync(file: string, options: Buffer): Promise<void>

export declare function bundlessFileAsync(file: string, options: Buffer): Promise<void>

export declare function bundlessFilesAsync(options: Buffer): Promise<void>

export declare function transformDtsAsync(file: string, options: Buffer): Promise<string>
